### ISSUE TITLE
Cannot build pendulum

### ISSUE THREAD

**Issue by Glavic** [titpetric/pendulum#4]
While running `go build` I get error:

```
main.go:13:2: cannot find package "app/assets" in any of:
        C:\dev\programs\go\src\app\assets (from $GOROOT)
        C:\dev\programs\go\_path\src\app\assets (from $GOPATH)
```

https://github.com/titpetric/pendulum/blob/7c261c3a015a21c93bb72230868d5506909de06d/main.go#L13

Where is this app/assets located?

**Comment by titpetric** [comment]
Hey. You should follow the steps from codeship-steps.yml. You'll need docker as well, even if, *technically*, you could put everything together without it. It does require node+npm+many things for the front-end, `go generate` for the assets, and then other things...

If you want to do it by hand:

- you can: `go get -u github.com/titpetric/pendulum` (or something like it)
- go to your `go/src/github...pendulum` folder and build the front end with `cd front && ./build.sh`
- run `go generate` which will create the assets files to be compiled into pendulum,
- and `go build -o pendulum cmd/pendulum/*.go` to produce the final binary

Or just grab any of them from the releases page.
